### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Chaostheorie** [KaneGreen/totp_rfc6238#1]
Hey! Thank you, for your work on a clean TOPT implementation for rust. I just wanted to ask if it would be possible to create some tests for the library in order to verify the functionality and ensure everything is working as expected.

I can also attempt to create some tests, though I would love to hear your opinion on this topic before starting anything unwanted :)

**Comment by KaneGreen** [comment]
Thank you very much for your recognition and feedback.

Currently, only a small amount of code in this crate is marked with `#[test]`. Other tests are mainly provided by document tests (`/// # Example`). You can see that these tests can be run when using `cargo test`. 
I think that if a function already has the correct documentation test, it is unnecessary to add a test to it in the tests module, and vice versa. Unless a new test can more comprehensively test an important function.

Although these tests have not covered almost all functions. But it seems that they are working properly and there is no major problem with the entire crate.

If your time is limited, I think the existing test is sufficient.

If you have plenty of energy and care about the completeness of the test, you can consider adding and improving some tests.
for example:
1. The document test of `high_level::TotpGenerator::get_code_window()` currently takes about 1 second. Even if this is acceptable to most people, I don't know if anyone will be dissatisfied with this test. Maybe it can be modified.
2. Many methods of `high_level::TotpGenerator` are not tested. (Actually these methods are called in the tests of other methods.) Maybe they can be added.

Anyhow, Pull Requests are always welcomed.

Finally, thank you again for your feedback. Have a nice day.

**Comment by Chaostheorie** [comment]
Thank you for the quick and detailed response. I'm relatively new to rust and hadn't found the tests you mentioned. Those tests already cover a lot of the parts, which concerned me, but I will try to look into writing tests for the parts you mentioned, when I have some free time next week.

I will close this issue then.
